""" 
Snakemakerule to create input and run simulation 
"""
import os
import sys

DATA_DIR = 'data'
RES_DIR = 'results'

rule all:
    input: os.path.join(RES_DIR, 'results.json')

rule run_simulation:
    input: 
        network = os.path.join(DATA_DIR, "infosys_network.gml"),
        configfile = os.path.join(DATA_DIR, 'config.json')
    output: 
        measurements = os.path.join(RES_DIR, 'results.json'),
        tracking = os.path.join(RES_DIR, 'tracking.json.gz')
    shell: """
        python3 -m workflow.scripts.driver -i {input.network} -o {output.measurements} -v {output.tracking} --config {input.configfile} --times 1
    """

rule init_net:
    input: 
        follower = os.path.join(DATA_DIR, 'follower_network.gml'),
        configfile = os.path.join(DATA_DIR, 'config.json')
        
    output: os.path.join(DATA_DIR, "infosys_network.gml")

    shell: """
            python3 -m workflow.scripts.init_net -i {input.follower} -o {output} --config {input.configfile} --times 1
        """ 